module ListingData
  AREAS = ["Agassiz",
           "Airport",
           "Alpine Place",
           "Amber Trails",
           "Archwood",
           "Armstrong Point",
           "Beaumont",
           "Betsworth",
           "Birchwood",
           "Booth",
           "Bridgewater Forest",
           "Broadway - Assiniboine",
           "Brockville",
           "Brooklands",
           "Bruce Park",
           "Buchanan",
           "Burrows - Keewatin",
           "Burrows Central",
           "Canterbury Park",
           "Centennial",
           "Central Park",
           "Central River Heights",
           "Central St. Boniface",
           "Chalmers",
           "Champlain",
           "China Town",
           "Cloutier Drive",
           "Colony",
           "Crescent Park",
           "Crescentwood",
           "Crestview",
           "Dakota Crossing",
           "Daniel McIntyre",
           "Deer Lodge",
           "Downtown Winnipeg",
           "Dufferin",
           "Dufresne",
           "Eaglemere",
           "Earl Grey",
           "East Elmwood",
           "Ebby - Wentworth",
           "Edgeland",
           "Elm Park",
           "Elmhurst",
           "Elmwood",
           "Eric Coy",
           "Exchange District",
           "Fort Richmond",
           "Fort Rouge",
           "Garden City",
           "Garden Grove",
           "Glendale",
           "Glenelm",
           "Glenwood",
           "Grant Park",
           "Grassie",
           "Heritage Park",
           "Holden",
           "Inkster - Faraday",
           "Inkster Gardens",
           "Island Lakes",
           "J.B. Mitchell",
           "Jameswood",
           "Jefferson",
           "Kensington",
           "Kern Park",
           "Kil-cona Park",
           "Kildare - Redonda",
           "Kildonan Drive",
           "King Edward",
           "Kingston Crescent",
           "Kirkfield",
           "Lakeside Meadows",
           "Lavalee",
           "Leila - McPhillips Triangle",
           "Linden Woods",
           "Logan - C.P.R",
           "Lord Roberts",
           "Lord Selkirk Park",
           "Luxton",
           "Maginot",
           "Mandalay West",
           "The Maples",
           "Margaret Park",
           "Marlton",
           "Mathers",
           "Maybank",
           "McMillan",
           "Meadowood",
           "Meadows",
           "Melrose",
           "Minnetonka",
           "Minto",
           "Mission Gardens",
           "Montcalm",
           "Munroe East",
           "Munroe West",
           "Mynarski",
           "Niakwa Park",
           "Niakwa Place",
           "Norberry",
           "Normand Park",
           "North Point Douglas",
           "North River Heights",
           "North St. Boniface",
           "Norwood East",
           "Norwood West",
           "Old Tuxedo",
           "Osborne Village",
           "Parc La Salle",
           "Peguis",
           "Pembina Strip",
           "Point Road",
           "Polo Park",
           "Portage - Ellice",
           "Pulberry",
           "Radisson",
           "Richmond Lakes",
           "Richmond West",
           "Ridgedale",
           "Ridgewood South",
           "Riel",
           "River - Osborne",
           "River East",
           "River Heights",
           "River Park South",
           "River West Park",
           "Riverbend",
           "Rivergrove",
           "Riverview",
           "Robertson",
           "Roblin Park",
           "Rockwood",
           "Roslyn",
           "Rosser - Old Kildonan",
           "Rossmere - A",
           "Rossmere - B",
           "Royalwood",
           "Sage Creek",
           "Sargent Park",
           "Seven Oaks",
           "Shaughnessy Park",
           "Silver Heights",
           "Sir John Franklin",
           "South Point Douglas",
           "South Pointe",
           "South Portage",
           "South River Heights",
           "South Tuxedo",
           "Southboine",
           "Southdale",
           "Southland Park",
           "Spence",
           "Springfield North",
           "Springfield South",
           "St. George",
           "St. John's Park",
           "St. John's",
           "St. Matthews",
           "St. Norbert",
           "St. Vital Perimeter South",
           "Sturgeon Creek",
           "Talbot - Grey",
           "Templeton - Sinclair",
           "The Maples",
           "Tissot",
           "Trappistes",
           "Tuxedo",
           "Tyndall Park",
           "University",
           "Valhalla",
           "Valley Gardens",
           "Varennes",
           "Varsity View",
           "Vialoux",
           "Victoria Crescent",
           "Victoria West",
           "Vista",
           "Waverley Heights",
           "Wellington Crescent",
           "West Alexander",
           "West Broadway",
           "West Wolseley",
           "Westdale",
           "Weston",
           "Westwood",
           "Whyte Ridge",
           "Wildwood",
           "Wildwood Park",
           "Wilkes South",
           "William Whyte",
           "Windsor Park",
           "Wolseley",
           "Woodhaven",
           "Worthington"]

  PROVINCES = {"Alberta" => "AB",
               "British Columbia" => "BC",
               "Manitoba" => "MB",
               "New Brunswick" => "NB",
               "Newfoundland and Labrador" => "NL",
               "Nova Scotia" => "NS", 
               "Nunavut" => "NU",
               "Ontario" => "ON",
               "Prince Edward Island" => "PE",
               "Quebec" => "QC",
               "Saskatchewan" => "SK",
               "Northwest Territories" => "NT",
               "Yukon" => "YT" }

  STYLES = ["Bungalow", 
           "1 1/2",
           "1 3/4",
           "2 1/2",
           "Bilevel",
           "Cab-over",
           "Split - 3 Level",
           "Split - 4 Level",
           "Split - Multi-Level",
           "Two Storeys"]

  PROPERTY_TYPES = ["Duplex", 
                    "Mobile Home",
                    "Resort Property",
                    "Residential Detached",
                    "Single Family Detached",
                    "Single Family Attached",
                    "Townhouse",
                    "Vacant Land"]
  

end